// ignore: non_constant_identifier_names
List<String> list_of_disease = [
    "(Vertigo) Paroxysmal Positional Vertigo",
"AIDS",
"Acne",
"Alcoholic hepatitis",
"Allergy",
"Arthritis",
"Bronchial Asthma",
"Cervical spondylosis",
"Chicken pox",
"Chronic cholestasis",
"Common Cold",
"Dengue",
"Diabetes",
"Dimorphic hemorrhoids (piles)",
"Drug Reaction",
"Fungal infection",
"GERD",
"Gastroenteritis",
"Heart attack",
"Hepatitis B",
"Hepatitis C",
"Hepatitis D",
"Hepatitis E",
"Hypertension",
"Hyperthyroidism",
"Hypoglycemia",
"Hypothyroidism",
"Impetigo",
"Jaundice",
"Malaria",
"Migraine",
"Osteoarthritis",
"Paralysis (brain hemorrhage)",
"Peptic ulcer disease",
"Pneumonia",
"Psoriasis",
"Tuberculosis",
"Typhoid",
"Urinary tract infection",
"Varicose veins",
"Hepatitis A",
];